#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOURCE="$SCRIPT_DIR/skills/build-standard-project"

if [ ! -f "$SOURCE/SKILL.md" ]; then
  printf '%s\n' "Invalid release: SKILL.md is missing from $SOURCE" >&2
  exit 1
fi

CODEX_INSTALL_ROOT=${CODEX_HOME:-"$HOME/.codex"}
CLAUDE_INSTALL_ROOT=${CLAUDE_CONFIG_DIR:-"$HOME/.claude"}
AGENTS_INSTALL_ROOT=${AGENTS_HOME:-"$HOME/.agents"}

install_skill() {
  INSTALL_NAME=$1
  INSTALL_BASE=$2
  SKILLS_DIRECTORY="$INSTALL_BASE/skills"
  TARGET="$SKILLS_DIRECTORY/build-standard-project"

  mkdir -p "$SKILLS_DIRECTORY"

  BACKUP=''
  if [ -e "$TARGET" ]; then
    TIMESTAMP=$(date '+%Y%m%d-%H%M%S')
    BACKUP="$TARGET.backup-$TIMESTAMP"
    mv "$TARGET" "$BACKUP"
  fi

  if ! cp -R "$SOURCE" "$TARGET"; then
    if [ -n "$BACKUP" ] && [ ! -e "$TARGET" ] && [ -e "$BACKUP" ]; then
      mv "$BACKUP" "$TARGET"
    fi
    exit 1
  fi

  printf '%s\n' "Installed build-standard-project 1.9.0 for $INSTALL_NAME to $TARGET"
  if [ -n "$BACKUP" ]; then
    printf '%s\n' "Previous installation backed up to $BACKUP"
  fi
}

install_skill Codex "$CODEX_INSTALL_ROOT"
if [ "$CLAUDE_INSTALL_ROOT" != "$CODEX_INSTALL_ROOT" ]; then
  install_skill Claude "$CLAUDE_INSTALL_ROOT"
fi
if [ "$AGENTS_INSTALL_ROOT" != "$CODEX_INSTALL_ROOT" ] && [ "$AGENTS_INSTALL_ROOT" != "$CLAUDE_INSTALL_ROOT" ]; then
  install_skill Agents "$AGENTS_INSTALL_ROOT"
fi

printf '%s\n' 'The Skill will be available to Codex, Claude, and compatible agents from their next conversation.'
printf '%s\n' 'Existing project-local AGENTS.md, package.json, and CI are unchanged; use the legacy migration command for projects generated by v1.1-v1.6.'
