[CmdletBinding()]
param(
    [string]$InstallRoot = $env:CODEX_HOME,
    [string]$AgentsRoot = $env:AGENTS_HOME
)

$ErrorActionPreference = 'Stop'

$source = Join-Path $PSScriptRoot 'skills\build-standard-project'
if (-not (Test-Path -LiteralPath (Join-Path $source 'SKILL.md') -PathType Leaf)) {
    throw "Invalid release: SKILL.md is missing from $source"
}

if ([string]::IsNullOrWhiteSpace($InstallRoot)) {
    $InstallRoot = Join-Path $env:USERPROFILE '.codex'
}
if ([string]::IsNullOrWhiteSpace($AgentsRoot)) {
    $AgentsRoot = Join-Path $env:USERPROFILE '.agents'
}

$locations = @(
    @{ Name = 'Codex'; Root = $InstallRoot },
    @{ Name = 'Agents'; Root = $AgentsRoot }
)
$installedTargets = @{}

foreach ($location in $locations) {
    $skillsDirectory = [IO.Path]::GetFullPath((Join-Path $location.Root 'skills'))
    $target = [IO.Path]::GetFullPath((Join-Path $skillsDirectory 'build-standard-project'))
    if (-not $target.StartsWith($skillsDirectory + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing installation target outside the skills directory: $target"
    }
    if ($installedTargets.ContainsKey($target)) {
        continue
    }

    New-Item -ItemType Directory -Path $skillsDirectory -Force | Out-Null
    $backup = $null
    if (Test-Path -LiteralPath $target) {
        $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backup = "$target.backup-$timestamp"
        Move-Item -LiteralPath $target -Destination $backup
    }

    try {
        Copy-Item -LiteralPath $source -Destination $target -Recurse
    }
    catch {
        if ($backup -and -not (Test-Path -LiteralPath $target) -and (Test-Path -LiteralPath $backup)) {
            Move-Item -LiteralPath $backup -Destination $target
        }
        throw
    }

    $installedTargets[$target] = $true
    Write-Host "Installed build-standard-project 1.8.3 for $($location.Name) to $target"
    if ($backup) {
        Write-Host "Previous installation backed up to $backup"
    }
}
Write-Host 'The Skill will be available to Codex and compatible agents from their next conversation.'
Write-Host 'Existing project-local AGENTS.md, package.json, and CI are unchanged; use the legacy migration command for projects generated by v1.1-v1.6.'
